jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  fastlane_release:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: bundle exec fastlane android release
          name: Run Fastlane
  android_build:
    executor: rn/linux_js
    steps:
      - run:
          command: sudo npm install -g react-native-cli
          name: react-native cli install
      - run:
          command: yarn install
          name: yarn install
      - run:
          command: react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/release/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/release
          name: react-native bundle
      - run:
          command: cd android && ./gradlew assembleRelease
          name: gradlew assembleRelease
orbs:
  rn: react-native-community/react-native@1.0.0
version: 2.1
workflows:
  test:
    jobs:
      - android_build:
          requires:
            - checkout_code
      # - rn/android_test:
      #     requires:
      #       - rn/android_build
      # - fastlane_release:
      #     requires:
      #       - rn/android_test
