jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
  android_build:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          command: yarn install
          name: yarn install
      - run:
          command: sudo npm install -g react-native-cli
          name: react-native cli install
      - run:
          command: mkdir -p android/app/build/intermediates/assets/release
          name: mkdir -p android/app/build/intermediates/assets/release
      - run:
          command: react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/release/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/release
          name: react-native bundle
      - run:
          command: |
            echo 'export PATH="$PATH:/usr/local/opt/node@8/bin:~/.yarn/bin:~/project/node_modules/.bin:~/project/example/node_modules/.bin"' >> $BASH_ENV
            echo 'export ANDROID_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export PATH="$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH"' >> $BASH_ENV
            echo 'export QEMU_AUDIO_DRV=none' >> $BASH_ENV
            echo 'export JAVA_HOME=/Library/Java/Home' >> $BASH_ENV
            source $BASH_ENV
          name: Configure Environment Variables
      - restore_cache:
        key: |
          brew-cache-{{ arch }}-{{ .Environment.CACHE_VERSION }}
      - run:
          command: cd android && ./gradlew assembleRelease
          name: gradlew assembleRelease
orbs:
  rn: react-native-community/react-native@1.0.0
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - android_build:
          requires:
            - analyse_js
